const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923014077187";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_02_00_09_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDgsXG4gICAgICAgIDc4LFxuICAgICAgICAxMjksXG4gICAgICAgIDEwNixcbiAgICAgICAgMTMwLFxuICAgICAgICA4LFxuICAgICAgICAyNTQsXG4gICAgICAgIDI2LFxuICAgICAgICAyOCxcbiAgICAgICAgMTI3LFxuICAgICAgICA0NyxcbiAgICAgICAgMjM1LFxuICAgICAgICA3MCxcbiAgICAgICAgMTcsXG4gICAgICAgIDc5LFxuICAgICAgICA3NCxcbiAgICAgICAgMjU1LFxuICAgICAgICAxNTQsXG4gICAgICAgIDExLFxuICAgICAgICAxNCxcbiAgICAgICAgNyxcbiAgICAgICAgMTEzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTY5LFxuICAgICAgICAxMDQsXG4gICAgICAgIDQ0LFxuICAgICAgICAxNTAsXG4gICAgICAgIDcxLFxuICAgICAgICAyOCxcbiAgICAgICAgOTFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjM1LFxuICAgICAgICAxMzUsXG4gICAgICAgIDkyLFxuICAgICAgICA3OCxcbiAgICAgICAgMjIxLFxuICAgICAgICAxNzIsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTg3LFxuICAgICAgICA3OCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxNjAsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTgyLFxuICAgICAgICAxOTQsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMDIsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMzIsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTU1LFxuICAgICAgICA1NCxcbiAgICAgICAgMjIyLFxuICAgICAgICA1NyxcbiAgICAgICAgMTExLFxuICAgICAgICA2MixcbiAgICAgICAgMjMyLFxuICAgICAgICAxNDMsXG4gICAgICAgIDg0LFxuICAgICAgICAyMjEsXG4gICAgICAgIDQ5LFxuICAgICAgICAxMjZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2LFxuICAgICAgICAxMTksXG4gICAgICAgIDU4LFxuICAgICAgICAyMzksXG4gICAgICAgIDIzMyxcbiAgICAgICAgOTYsXG4gICAgICAgIDk0LFxuICAgICAgICAxNzUsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxMSxcbiAgICAgICAgMjYsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjM1LFxuICAgICAgICA2MSxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMzUsXG4gICAgICAgIDI1NCxcbiAgICAgICAgOTUsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTgwLFxuICAgICAgICA4OCxcbiAgICAgICAgMjIsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjA3LFxuICAgICAgICAyNTEsXG4gICAgICAgIDYwLFxuICAgICAgICAyMzQsXG4gICAgICAgIDE0LFxuICAgICAgICAyMTYsXG4gICAgICAgIDExNixcbiAgICAgICAgMTI2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjA3LFxuICAgICAgICAxMjUsXG4gICAgICAgIDQyLFxuICAgICAgICAxNTksXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjMxLFxuICAgICAgICA2LFxuICAgICAgICAyMCxcbiAgICAgICAgMjIsXG4gICAgICAgIDcsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjExLFxuICAgICAgICAxMTksXG4gICAgICAgIDczLFxuICAgICAgICAxOTAsXG4gICAgICAgIDg0LFxuICAgICAgICAxODksXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxMTQsXG4gICAgICAgIDQ5LFxuICAgICAgICAxNDcsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjQyLFxuICAgICAgICAxMjEsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNCxcbiAgICAgICAgMTA5LFxuICAgICAgICA2NyxcbiAgICAgICAgMTAsXG4gICAgICAgIDQ4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDQsXG4gICAgICAgIDgzLFxuICAgICAgICAxLFxuICAgICAgICA3OCxcbiAgICAgICAgMjA3LFxuICAgICAgICA3NixcbiAgICAgICAgMTc5LFxuICAgICAgICAyMDUsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMzYsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTgyLFxuICAgICAgICAxMjIsXG4gICAgICAgIDI0LFxuICAgICAgICAyNCxcbiAgICAgICAgMjIzLFxuICAgICAgICAyMjgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgNCxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNDgsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTAxLFxuICAgICAgICAyMTQsXG4gICAgICAgIDM3LFxuICAgICAgICA5NCxcbiAgICAgICAgMjgsXG4gICAgICAgIDYsXG4gICAgICAgIDkzLFxuICAgICAgICAxMTMsXG4gICAgICAgIDY5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjM3LFxuICAgICAgICAyMixcbiAgICAgICAgMjIwLFxuICAgICAgICAxNzksXG4gICAgICAgIDE2LFxuICAgICAgICAxMDYsXG4gICAgICAgIDcyLFxuICAgICAgICAxNDQsXG4gICAgICAgIDc4LFxuICAgICAgICAyNDEsXG4gICAgICAgIDU1LFxuICAgICAgICAxMDcsXG4gICAgICAgIDcxLFxuICAgICAgICAzLFxuICAgICAgICAyNyxcbiAgICAgICAgOTQsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTY0LFxuICAgICAgICAxNSxcbiAgICAgICAgMjI3LFxuICAgICAgICAyNDAsXG4gICAgICAgIDExNSxcbiAgICAgICAgODcsXG4gICAgICAgIDIxNixcbiAgICAgICAgOTEsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjM1LFxuICAgICAgICA1MSxcbiAgICAgICAgMzQsXG4gICAgICAgIDc5LFxuICAgICAgICAxM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAzMixcbiAgICAgICAgICA2NixcbiAgICAgICAgICA5M1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDE2MSxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICA5LFxuICAgICAgICAgIDExOVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQ4LFxuICAgICAgICAxNzUsXG4gICAgICAgIDMzLFxuICAgICAgICA4OCxcbiAgICAgICAgNDksXG4gICAgICAgIDc4LFxuICAgICAgICAxNTksXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMzEsXG4gICAgICAgIDEyLFxuICAgICAgICAyMTksXG4gICAgICAgIDY2LFxuICAgICAgICAxNzYsXG4gICAgICAgIDQ4LFxuICAgICAgICAzNyxcbiAgICAgICAgODAsXG4gICAgICAgIDMxLFxuICAgICAgICA1MyxcbiAgICAgICAgMTkwLFxuICAgICAgICA0MyxcbiAgICAgICAgODEsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNjMsXG4gICAgICAgIDE1NSxcbiAgICAgICAgODksXG4gICAgICAgIDEwOCxcbiAgICAgICAgNixcbiAgICAgICAgMjEzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDg2LFxuICAgICAgICA1MSxcbiAgICAgICAgMTc2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxNDEsXG4gICAgICAgIDEzLFxuICAgICAgICAxMTcsXG4gICAgICAgIDIyLFxuICAgICAgICAxNDcsXG4gICAgICAgIDI4LFxuICAgICAgICA2NCxcbiAgICAgICAgMjE2LFxuICAgICAgICAzMCxcbiAgICAgICAgMTk1LFxuICAgICAgICAxMzAsXG4gICAgICAgIDEzMCxcbiAgICAgICAgOCxcbiAgICAgICAgMTcwLFxuICAgICAgICA0NSxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTIxLFxuICAgICAgICAxOTYsXG4gICAgICAgIDEwOCxcbiAgICAgICAgNTEsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMjgsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTI2LFxuICAgICAgICAxMzFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDg3LFxuICBcImFkdlNlY3JldEtleVwiOiBcIi80bWIzcTNZU2hoWXh2VVpZaGZIQ2RUd1AzT3BaTUsxNWtlWlp1VVZZRTQ9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMDE0MDc3MTg3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI2QkM1NkNDRDBENzNBQUMyMkU2QUQyRDBGNUJDNEFFM1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjU1MDE2MDZcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiRVZDd2hEdTJTRlc3cl9GTUxpNVN5d1wiLFxuICBcInBob25lSWRcIjogXCJiYjIxMTJhNC1hMjUyLTQwN2MtYjNhZC1mNmIxNjI0NmQzZjRcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTAzLFxuICAgICAgMjA2LFxuICAgICAgMTc1LFxuICAgICAgMjU0LFxuICAgICAgMTgsXG4gICAgICA0OSxcbiAgICAgIDE2MSxcbiAgICAgIDQwLFxuICAgICAgMTQsXG4gICAgICA5NCxcbiAgICAgIDEzMCxcbiAgICAgIDExMCxcbiAgICAgIDk4LFxuICAgICAgNjgsXG4gICAgICAyMzIsXG4gICAgICAyNDAsXG4gICAgICAxMTAsXG4gICAgICAyMjgsXG4gICAgICAxMDYsXG4gICAgICAyMDFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjQ3LFxuICAgICAgNTcsXG4gICAgICAyMTIsXG4gICAgICAxNDEsXG4gICAgICA4MyxcbiAgICAgIDE3MCxcbiAgICAgIDE1OCxcbiAgICAgIDIxNCxcbiAgICAgIDE0NSxcbiAgICAgIDI0MyxcbiAgICAgIDEwMSxcbiAgICAgIDE3NCxcbiAgICAgIDIwNCxcbiAgICAgIDExNixcbiAgICAgIDIyMSxcbiAgICAgIDk1LFxuICAgICAgOTcsXG4gICAgICAxNjAsXG4gICAgICAyMjgsXG4gICAgICAxODZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiMUFKNjkxMlRcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzAxNDA3NzE4NzoyN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMjMzNjU5MjIzMjU3MTExOjI3QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ09mK21zY0dFSjZoNUxZR0dBWWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiQ0QyUmgrSUY2RUZiYTNqMkVtckcvb1lPaVg5eDNMRkluSjY1MnJBWkhEdz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJQeThEN3E2Vk1NcVF4Y1EvbFMyQTQxUzJFQjRnbXBxYXNXdXJpTGpxazNBN3pwWVVKdEt3bEUyYXEva1J1Q0oxL3hUUFpFUkorR0VWUm5TSDlyZFRDUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJyeWhRaFFyelR0WjE5eFpacU1INUZickdFM2tCYzNoRWlaSVFJbEZoQW5RVzd5b3AwQVVLM0dqWjdOUURvcTBOaVpMczlpWmJPaXNnOXFsUFdidUtpUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMwMTQwNzcxODc6MjdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMjgsXG4gICAgICAgICAgNjBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyNTUwMTYwMixcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUtFRFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS0VELmpzb24iOiAie1wia2V5RGF0YVwiOlwiTWlFeTZRY1dyR2VmZkF0UGZVY3hIdUJHOVlyak44K01hdkVCdmd0WHhUOD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNzU5OTUyNzQzLFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
